### ISSUE TITLE
evaluate ArgoCD

### ISSUE THREAD

**Issue by ismailbay** [ismailbay/home-infra#4]
# Sources

# Tasks
- [x] deploy Argo CD
- [x] create stacks using base manifests
- [x] ~~deploy Gitea~~
- [x] ~~connect Gitea to Argo CD~~
- [x] ~~add github as push mirror to Gitea~~

# Improvements
