### ISSUE TITLE
install base components in k3s

### ISSUE THREAD

**Issue by ismailbay** [ismailbay/home-infra#6]
- [x] ingress-nginx
- [x] cert-manager
- [x] loki and promtail
- [x] kube-prometheus-stack
- [x] hajimari
- [x] descheduler
- [x] kured

out of scope in this issue:
- [x] ~~cloudflared~~ moved to issue #8
- [x] ~~external-dns~~ moved to issue #8
- [x] ~~nfs-subdir-external-provisioner~~ moved to issue #7
